run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - golint
    - ineffassign
    - misspell
    - staticcheck
    - unused
    - errcheck
    - gosimple
    - deadcode
    - varcheck
    - structcheck
    - typecheck
    - gocyclo
    - gosec
    - unconvert
    - gocritic
    - gofumpt
    - revive
    - exportloopref
    - gomodguard
    - depguard

linters-settings:
  gocyclo:
    min-complexity: 15
  
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
  
  revive:
    rules:
      - name: exported
        arguments: [checkPrivateReceivers]
      - name: var-naming
      - name: package-comments
      - name: function-result-limit
        arguments: [3]
      - name: argument-limit
        arguments: [5]
      - name: cyclomatic
        arguments: [15]
  
  gosec:
    excludes:
      - G204 # Command execution with variable input
      - G304 # File path provided as taint input

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - gocritic
    - path: cmd/
      linters:
        - gocritic
    - source: "^//go:embed"
      linters:
        - misspell
  
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true