// Code generated by spicedb-gen, DO NOT EDIT.

package bookingsvc

import (
  "github.com/danhtran94/authzed-codegen/pkg/authz"

  
)

const TypeCustomer authz.Type = "bookingsvc/customer"
type RelationCustomer authz.Relation
type PermissionCustomer authz.Permission


type Customer authz.ID

