// Code generated by spicedb-gen, DO NOT EDIT.

package bookingsvc

import (
  "github.com/danhtran94/authzed-codegen/pkg/authz"

  
)

const TypeUser authz.Type = "bookingsvc/user"
type RelationUser authz.Relation
type PermissionUser authz.Permission


type User authz.ID

