package codegen

import (
	"bytes"
	"fmt"

	"github.com/dave/jennifer/jen"
	"github.com/oitnes/authzed-codegen/internal/generator/ast"
	"github.com/oitnes/authzed-codegen/internal/generator/naming"
)

// generateClientFile generates a client.go file containing a Client struct that
// holds the engine (and optionally repo) and exposes factory methods for every
// definition type so callers never have to pass the engine individually.
func generateClientFile(schema *ast.Schema, opts Options) (*GeneratedFile, error) {
	f := jen.NewFile(opts.PackageName)
	f.HeaderComment("Code generated by authzed-codegen. DO NOT EDIT.")

	// Struct fields
	fields := []jen.Code{
		jen.Id("engine").Qual(authzPkg, "Engine"),
	}
	if opts.WithRepository {
		fields = append(fields, jen.Id("repo").Qual(authzPkg, "Repository"))
	}

	f.Comment("Client is a factory for creating permission entities backed by a shared engine.")
	f.Type().Id("Client").Struct(fields...)
	f.Line()

	// Constructor
	params := []jen.Code{
		jen.Id("engine").Qual(authzPkg, "Engine"),
	}
	initFields := jen.Dict{
		jen.Id("engine"): jen.Id("engine"),
	}
	if opts.WithRepository {
		params = append(params, jen.Id("repo").Qual(authzPkg, "Repository"))
		initFields[jen.Id("repo")] = jen.Id("repo")
	}

	f.Comment("NewClient creates a new Client with the given engine.")
	f.Func().Id("NewClient").Params(params...).Op("*").Id("Client").Block(
		jen.Return(jen.Op("&").Id("Client").Values(initFields)),
	)
	f.Line()

	// Engine() accessor for callers that need raw engine access
	f.Comment("Engine returns the underlying authorization engine.")
	f.Func().Params(jen.Id("c").Op("*").Id("Client")).Id("Engine").Params().Qual(authzPkg, "Engine").Block(
		jen.Return(jen.Id("c").Dot("engine")),
	)
	f.Line()

	// One factory method per definition type
	for _, def := range schema.Definitions {
		typeName := naming.TypeStructName(def.Name)
		constructorArgs := []jen.Code{
			jen.Id("id"),
			jen.Id("c").Dot("engine"),
		}
		if opts.WithRepository {
			constructorArgs = append(constructorArgs, jen.Id("c").Dot("repo"))
		}

		methodName := "New" + typeName
		f.Commentf("%s creates a new %s entity backed by the client's engine.", methodName, typeName)
		f.Func().Params(jen.Id("c").Op("*").Id("Client")).Id(methodName).Params(
			jen.Id("id").String(),
		).Id(typeName).Block(
			jen.Return(jen.Id("New"+typeName).Call(constructorArgs...)),
		)
		f.Line()
	}

	var buf bytes.Buffer
	if err := f.Render(&buf); err != nil {
		return nil, fmt.Errorf("rendering client: %w", err)
	}

	return &GeneratedFile{Name: "client.go", Content: buf.String()}, nil
}
