package codegen

import (
	"bytes"
	"fmt"
	"sort"

	"github.com/dave/jennifer/jen"
	"github.com/oitnes/authzed-codegen/internal/generator/ast"
	"github.com/oitnes/authzed-codegen/internal/generator/naming"
)

const authzPkg = "github.com/oitnes/authzed-codegen/pkg/authz"

// newEntityCall builds a New<typeName>(id, <receiver>.engine[, <receiver>.repo]) jennifer expression.
func newEntityCall(typeName, receiver string, withRepo bool) jen.Code {
	args := []jen.Code{
		jen.String().Call(jen.Id("id")),
		jen.Id(receiver).Dot("engine"),
	}
	if withRepo {
		args = append(args, jen.Id(receiver).Dot("repo"))
	}
	return jen.Id("New" + typeName).Call(args...)
}

// Options controls code generation behavior.
type Options struct {
	PackageName    string
	WithRepository bool
}

// GeneratedFile represents a generated Go source file.
type GeneratedFile struct {
	Name    string
	Content string
}

// Generate produces Go source files from the parsed AST.
func Generate(schema *ast.Schema, opts Options) ([]*GeneratedFile, error) {
	g := &generator{
		schema: schema,
		opts:   opts,
	}
	return g.generate()
}

type generator struct {
	schema *ast.Schema
	opts   Options
}

func (g *generator) generate() ([]*GeneratedFile, error) {
	var files []*GeneratedFile

	for _, def := range g.schema.Definitions {
		file, err := g.generateDefinitionFile(def)
		if err != nil {
			return nil, fmt.Errorf("generating %s: %w", def.Name, err)
		}
		files = append(files, file)
	}

	clientFile, err := generateClientFile(g.schema, g.opts)
	if err != nil {
		return nil, fmt.Errorf("generating client: %w", err)
	}
	files = append(files, clientFile)

	sort.Slice(files, func(i, j int) bool {
		return files[i].Name < files[j].Name
	})

	return files, nil
}

func (g *generator) generateDefinitionFile(def *ast.Definition) (*GeneratedFile, error) {
	f := jen.NewFile(g.opts.PackageName)
	f.HeaderComment("Code generated by authzed-codegen. DO NOT EDIT.")

	generateConstants(f, def)
	generateTypeDefinition(f, def, g.opts.WithRepository)
	generateRelationMethods(f, def, g.opts.WithRepository)

	generatedLookups := make(map[string]bool)
	generatePermissionMethods(f, def, generatedLookups, g.opts.WithRepository)

	if g.opts.WithRepository {
		generateRepositoryMethods(f, def)
	}

	var buf bytes.Buffer
	if err := f.Render(&buf); err != nil {
		return nil, fmt.Errorf("rendering %s: %w", def.Name, err)
	}

	fileName := naming.ToSnakeCase(def.Name) + ".go"
	return &GeneratedFile{Name: fileName, Content: buf.String()}, nil
}
