// Code generated by spicedb-gen, DO NOT EDIT.

package menusvc

import (
  "github.com/danhtran94/authzed-codegen/pkg/authz"

  
)

const TypeProduct authz.Type = "menusvc/product"
type RelationProduct authz.Relation
type PermissionProduct authz.Permission


type Product authz.ID

